### ISSUE TITLE
Link to formatNumber in "Creating your first Grails Application" is broken

### ISSUE THREAD

**Issue by Frankst2** [grails/grails-guides#12]
In section 7 of the "Creating your first Grails Application" guide (http://guides.grails.org/creating-your-first-grails-app/guide/index.html#services) the link to the formatNumber documentation is broken:

> <g:formatNumber> is another GSP tag which provides many useful options for rendering numbers, including currency and decimal precision. See the Grails documentation for more.

The link points to http://docs.grails.org/latest/ref/Tags/formatNumber.html which does not exist.

**Comment by niravassar** [comment]
thanks, not needed for the next version. I deleted it
