### ISSUE TITLE
Favicon Out Of Date

### ISSUE THREAD

**Issue by jeffscottbrown** [grails/grails-guides#19]
Many of our guides (not sure if it is all of them) have an outdated favicon.  See https://guides.grails.org/creating-your-first-grails-app/img/favicon.ico.

**Comment by wiesej** [comment]
Need to update favicon to Orange Grails circled logo.

**Comment by jeffscottbrown** [comment]
Separate, but related: https://github.com/grails/grails-core/issues/11723

**Comment by JasonTypesCodes** [comment]
Closed by #22
