### ISSUE TITLE
Problem With Guide Search

### ISSUE THREAD

**Issue by jeffscottbrown** [grails/grails-guides#20]
When I use the search box at http://guides.grails.org/ the view updates live based on the search criteria, as desired, but the items that show up in the results have broken links in them.

<img width="1176" alt="Screen Shot 2020-12-08 at 2 52 54 PM" src="https://user-images.githubusercontent.com/15482/101540137-2e86d300-3965-11eb-83c1-64a272732f8f.png">

The link behind `undefinedundefined` points to http://guides.grails.org/undefined.

**Comment by JasonTypesCodes** [comment]
This was fixed in grails/grails-static-website#171
