### ISSUE TITLE
Update Grails logo on the following guides to correct version

### ISSUE THREAD

**Issue by JasonTypesCodes** [grails/grails-guides#27]
https://guides.grails.org/neo4j-movies/guide/index.html
https://guides.grails.org/grails-rabbitmq/guide/index.html
https://guides.grails.org/grails-schwartz/guide/index.html
https://guides.grails.org/grails-vue-combined/guide/index.html
https://guides.grails.org/database-per-tenant/guide/index.html
https://guides.grails.org/grails-oauth-twitter/guide/index.html
https://guides.grails.org/grails-elasticsearch/guide/index.html
https://guides.grails.org/grails-quickcast-logging/guide/index.html
https://guides.grails.org/grails-quickcasts-json-views/guide/index.html
https://guides.grails.org/grails-docker-external-services/guide/index.html
https://guides.grails.org/grails-quickcasts-developing-grails-3-applications-with-intellij-idea/guide/index.html

**Comment by niravassar** [comment]
I need to wait for about 15 min for each commit to update so I will do a check all at once by tomorrow.  I did the top two successfully.

**Comment by niravassar** [comment]
also about 15 more guides that needed the same update. 00cd488a
