### ISSUE TITLE
Plugin [id: 'org.grails.grails-gsp'] was not found

### ISSUE THREAD

**Issue by monetschemist** [grails/grails-guides#30]
Grails Version: 6.2.0 Gradle Version: 7.6.4 JVM Version: 11.0.16.

Cloned the repository https://github.com/grails/grails-guides.git

Trying to create a new guide:
```
./create-guide.sh querying-gorm-dynamic-finders
```

fails as:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/clh/src/Grails6/Tutorials/grails-guides/querying-gorm-dynamic-finders/complete/build.gradle' line: 3

* What went wrong:
Plugin [id: 'org.grails.grails-gsp'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
```

This seems to be caused by the shell script executing the `gradle wrapper` command.

Not sure what other info might be useful

**Comment by jamesfredley** [comment]
Please retry with the `6.0.x` branch, it has been updated to be the default instead of `master`.

**Comment by monetschemist** [comment]
@jamesfredley I tried with the 6.0.x branch, but that continues to fail for me:
```
clh@montpellier:~/src/Grails6/Tutorials$ grails --version
Grails Version: 6.2.0
JVM Version: 11.0.16
clh@montpellier:~/src/Grails6/Tutorials$ gradle --version

------------------------------------------------------------
Gradle 7.6.4
------------------------------------------------------------

Build time:   2024-02-05 14:29:18 UTC
Revision:     e0bb3fc8cefad8432c9033cdfb12dc14facc9dd9

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.24 (Eclipse Adoptium 11.0.24+8)
OS:           Linux 6.8.0-45-generic amd64

clh@montpellier:~/src/Grails6/Tutorials$ git clone https://github.com/grails/grails-guides.git
Cloning into 'grails-guides'...
remote: Enumerating objects: 459179, done.
remote: Counting objects: 100% (63058/63058), done.
remote: Compressing objects: 100% (901/901), done.
remote: Total 459179 (delta 62204), reused 63011 (delta 62157), pack-reused 396121 (from 1)
Receiving objects: 100% (459179/459179), 115.99 MiB | 42.27 MiB/s, done.
Resolving deltas: 100% (445632/445632), done.
clh@montpellier:~/src/Grails6/Tutorials$ cd grails-guides
clh@montpellier:~/src/Grails6/Tutorials/grails-guides$ ./create-guide.sh dynfinders

| Application created at /home/clh/src/Grails6/Tutorials/grails-guides/dynfinders/dynfinders

FAILURE: Build failed with an exception.

* Where:
Build file '/home/clh/src/Grails6/Tutorials/grails-guides/dynfinders/complete/build.gradle' line: 3

* What went wrong:
Plugin [id: 'org.grails.grails-web'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 510ms
Guide created at location dynfinders/
clh@montpellier:~/src/Grails6/Tutorials/grails-guides$
```

What I see above that makes me wonder is this line:

Application created at `/home/clh/src/Grails6/Tutorials/grails-guides/dynfinders/dynfinders`

Seems like there's one too many "dynfinders" there?   Certainly there is no "dynfinders" subfolder in the "dynfinders" folder.

**Comment by monetschemist** [comment]
A bit more investigation... I see why there are two "dynfinders" in my above example (the lower one gets renamed to "initial" and then copied to "complete").  So that doesn't seem to be a problem, sorry for the distraction.

I notice that there are `gradle/wrapper` folders created in both `initial` and `complete`, but not in the upper level guide directory.  I suppose this is because the `gradle wrapper` command in the shell script successfully makes the `gradle/wrapper` folders in `initial` and `complete` but fails to make a `gradle/wrapper` folder in the main guide directory?

For clarity: the command `./create-guide test1` generates a `test1` folder that contains:
```
build.gradle
complete/
githubactions-build.sh
gradle.properties
initial/
settings.gradle
src/
```

The `test1/complete` folder contains:
```
build.gradle
buildSrc/
gradle/
gradle.properties
gradlew*
gradlew.bat
grails-app/
grails-cli.yml
README.md
settings.gradle
src/
```

**Comment by jamesfredley** [comment]
There were 2 pull requests outstanding and one addressed this issue.  If you pull the latest 6.0.x branch it should work.

https://github.com/grails/grails-guides/pull/28

**Comment by monetschemist** [comment]
@jamesfredley I just looked at the `create-guide.sh` script in the 6.0.x branch and I see the new `sed` command there.  I cloned the 6.0.x branch afresh and verified that the script now runs without errors.

Thanks to you and thanks to the person who created the fix!  Time to do some writing...
