### ISSUE TITLE
Wrong characters with accents

### ISSUE THREAD

**Issue by ilopmar** [grails/grails-guides#6]
It seems that the guide doesn't support characters with accents:

![accents](https://cloud.githubusercontent.com/assets/559192/25993902/f312bf96-370b-11e7-837e-ac9f98f3a6bb.png)

**Comment by sdelamo** [comment]
The bug must be in the Grails docs repo. I don't see we do anything fancy here with the properties: https://github.com/grails/grails-guides/blob/master/gradle/guide-build.gradle#L58

**Comment by jeffscottbrown** [comment]
<img width="725" alt="Screen Shot 2021-05-03 at 1 55 46 PM" src="https://user-images.githubusercontent.com/15482/116919841-80cbd780-ac17-11eb-98d0-a6f7f7afbdf7.png">

The current Guide site appears to be rendering accents.  @sdelamo @ilopmar Do you know if this issue can be closed or if it is still a concern?

**Comment by sdelamo** [comment]
I think it can be closed.
