### ISSUE TITLE
Ability to link to guides flagged with a particular tag

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-guides#8]
Right now when you click in React the guides filter only the REACT Guides:

![grails_guides](https://user-images.githubusercontent.com/864788/28471231-bd882b8c-6e3c-11e7-96af-c2a984445577.png)

We should achieve the same thing with a Url. 

That it is to say: 

guides.grails.org/#/index?tag=react should return only the react guides. or a similar URL structure

**Comment by benrhine** [comment]
So this is saying that we want to be able to filter on url params as well?

**Comment by jeffscottbrown** [comment]
> We should achieve the same thing with a Url.
> 
> That it is to say:
> 
> guides.grails.org/#/index?tag=react should return only the react guides. or a similar URL structure

We currently support a URL like https://guides.grails.org/tags/react.html.  @sdelamo Is your request specifically to support a request parameter to do similar?

**Comment by sdelamo** [comment]
No, I think we can close this issue. This is really old issue.  Probably before we added tag urls.
